-- AlterTable
ALTER TABLE "sessions" ADD COLUMN "consecutiveErrors" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "dailyMessageCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "jobCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "jobLimitReached" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "lastDailyReset" TIMESTAMP(3),
ADD COLUMN "lastErrorAt" TIMESTAMP(3),
ADD COLUMN "lastJobAt" TIMESTAMP(3),
ADD COLUMN "qualityScore" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN "restingUntil" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "contacts" ADD COLUMN "cooldownUntil" TIMESTAMP(3),
ADD COLUMN "lastMessageAt" TIMESTAMP(3),
ADD COLUMN "messageCount" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "messages" ADD COLUMN "lastAttemptAt" TIMESTAMP(3),
ADD COLUMN "lastSessionId" TEXT,
ADD COLUMN "maxRetries" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN "retryCount" INTEGER NOT NULL DEFAULT 0;
